apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: hwlim78/gaon-nginx:v1.0 # 실제 이미지로 수정하세요
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /var/www/html
          name: source-code
        - mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
          name: nginx-config
      volumes:
      - name: source-code
        hostPath:
          path: /home/yeshua/cka/study/gaon/source # 실제 경로로 수정하세요
      - name: nginx-config
        hostPath:
          path: /home/yeshua/cka/study/gaon/nginx
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  # type: LoadBalancer
  # type: ClusterIP
  type: NodePort
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30400

