
apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-controller3
  namespace: ingress-nginx
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: ingress-nginx
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
        #nodePort: 30130
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
        #nodePort: 30230
  externalIPs:
    - 192.168.100.72

