apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
    - name: myfrontend
      image: nginx
      volumeMounts:
      - mountPath: "/var/www/html"
        name: pv-vol1
  volumes:
    - name: pv-vol1
      persistentVolumeClaim:
        claimName: myclaim
