apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc
spec:
  resources:
    requests:
      storage: 500Mi
  accessModes:
  - ReadWriteMany
  storageClassName: local-storage                                         
