apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv
spec:
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Mi
  hostPath:
    path: /opt/log1

