
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: local-pv
spec:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: google-storage       
  resources:
   requests:
     storage: 500Mi
