apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pod-secrets-via-file
  name: pod-secrets-via-file
spec:
  containers:
  - image: redis
    name: pod-secrets-via-file
    volumeMounts:
        - name: super-secret
          readOnly: true
          mountPath: "/secrets"
  volumes:
    - name: super-secret
      secret:
        secretName: super-secret     
