apiVersion: v1
kind: Pod
metadata:
  name: web-liveness-test
spec:
  containers:
  - image: nginx
    name: web-liveness-test
    ports:
    - containerPort: 80
    livenessProbe:
      httpGet:
        path: /
        port: 80   
      initialDelaySeconds: 5
      periodSeconds: 10
      timeoutSeconds: 1
      successThreshold: 1
      failureThreshold: 3
      
