apiVersion: v1
data:
  INTERVAL: "10"
  OPTION: boy
  nginx-config.conf: |
    server {
        listen   80;
        server_name  www.example.com;

        gzip on;
        gzip_types text/plain application/xml;

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }
    }
kind: ConfigMap
metadata:
  name: ttabae-config
