apiVersion: v1
kind: Pod
metadata:
  name: webapp
spec:
  containers:
  - name: event-simulator
    image: kodekloud/event-simulator
    volumeMounts:
    - mountPath: /log
      name: webapp-volume
  volumes:
  - name: webapp-volume
    # mount /data/foo, but only if that directory already exists
    hostPath:
      path: /var/log/webapp # directory location on host
      type: Directory # this field is optional
